//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.1
//     from Assets/InputAction/Inventory.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Inventory: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Inventory()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Inventory"",
    ""maps"": [
        {
            ""name"": ""InGame"",
            ""id"": ""70c2f7e6-9438-46d3-be4a-43836ef61055"",
            ""actions"": [
                {
                    ""name"": ""PrevItem"",
                    ""type"": ""Value"",
                    ""id"": ""bd61b920-331f-4dff-af3f-dd58242af076"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""NextItem"",
                    ""type"": ""Value"",
                    ""id"": ""2984c8c6-56c2-4b61-af0f-ccdcab74a7c9"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Item1"",
                    ""type"": ""Button"",
                    ""id"": ""c61336ba-c6a7-4bf6-b202-6a2ce671773a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Item2"",
                    ""type"": ""Button"",
                    ""id"": ""32ccefd3-a44f-4b9c-84b8-7601ebc3d2c2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Item3"",
                    ""type"": ""Button"",
                    ""id"": ""07f31bde-063a-4362-806a-d92e3b17bbb1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Item4"",
                    ""type"": ""Button"",
                    ""id"": ""29979fe0-5309-4163-b7e4-6cfabecbff69"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Item5"",
                    ""type"": ""Button"",
                    ""id"": ""dcbe7e2d-a93b-4ccc-bc7a-2cfb4bf2f4fe"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Item6"",
                    ""type"": ""Button"",
                    ""id"": ""ff4b6383-1798-4187-9297-4d12bff8d737"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Item7"",
                    ""type"": ""Button"",
                    ""id"": ""8f627628-7330-4dca-8b85-be386f24ed76"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Item8"",
                    ""type"": ""Button"",
                    ""id"": ""9243031d-7336-41fc-8f05-e068abe71c8f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Item9"",
                    ""type"": ""Button"",
                    ""id"": ""823930c1-fab1-4da7-a101-ced3adeb7593"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""f8f721a5-917f-4d5e-bb62-a1b5cf7b4536"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NextItem"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""562bce76-b3e2-42b3-9b3c-b11f85cc8d56"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NextItem"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a8ab2423-19e9-4136-b8e5-f8dc3ebe41d0"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Item1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2ba9ea46-76ad-435c-bc48-0573017b86fe"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Item2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9baf078d-63f6-47cc-946d-33a495045fe6"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Item3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c6bb44a6-66ca-4af3-a686-d76a1e6e3918"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Item4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1c3ea53d-ad15-4097-8e53-7b0d477403d8"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Item5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""10537fe7-a7e8-400d-b2f7-72490cc640d0"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Item6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""beb52d44-918a-41e8-813b-4b2e7f7e6e2e"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Item7"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3b74ac52-a215-447a-911f-661acaab89e7"",
                    ""path"": ""<Keyboard>/8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Item8"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b7023248-d68b-41c6-88b0-e286f2ee1f7c"",
                    ""path"": ""<Keyboard>/9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Item9"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""69ad729e-5418-492f-b6af-8b5a0cb58232"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrevItem"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a8536620-6a3f-4fd5-9a0c-a75ff1d6bec0"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrevItem"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // InGame
        m_InGame = asset.FindActionMap("InGame", throwIfNotFound: true);
        m_InGame_PrevItem = m_InGame.FindAction("PrevItem", throwIfNotFound: true);
        m_InGame_NextItem = m_InGame.FindAction("NextItem", throwIfNotFound: true);
        m_InGame_Item1 = m_InGame.FindAction("Item1", throwIfNotFound: true);
        m_InGame_Item2 = m_InGame.FindAction("Item2", throwIfNotFound: true);
        m_InGame_Item3 = m_InGame.FindAction("Item3", throwIfNotFound: true);
        m_InGame_Item4 = m_InGame.FindAction("Item4", throwIfNotFound: true);
        m_InGame_Item5 = m_InGame.FindAction("Item5", throwIfNotFound: true);
        m_InGame_Item6 = m_InGame.FindAction("Item6", throwIfNotFound: true);
        m_InGame_Item7 = m_InGame.FindAction("Item7", throwIfNotFound: true);
        m_InGame_Item8 = m_InGame.FindAction("Item8", throwIfNotFound: true);
        m_InGame_Item9 = m_InGame.FindAction("Item9", throwIfNotFound: true);
    }

    ~@Inventory()
    {
        UnityEngine.Debug.Assert(!m_InGame.enabled, "This will cause a leak and performance issues, Inventory.InGame.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // InGame
    private readonly InputActionMap m_InGame;
    private List<IInGameActions> m_InGameActionsCallbackInterfaces = new List<IInGameActions>();
    private readonly InputAction m_InGame_PrevItem;
    private readonly InputAction m_InGame_NextItem;
    private readonly InputAction m_InGame_Item1;
    private readonly InputAction m_InGame_Item2;
    private readonly InputAction m_InGame_Item3;
    private readonly InputAction m_InGame_Item4;
    private readonly InputAction m_InGame_Item5;
    private readonly InputAction m_InGame_Item6;
    private readonly InputAction m_InGame_Item7;
    private readonly InputAction m_InGame_Item8;
    private readonly InputAction m_InGame_Item9;
    public struct InGameActions
    {
        private @Inventory m_Wrapper;
        public InGameActions(@Inventory wrapper) { m_Wrapper = wrapper; }
        public InputAction @PrevItem => m_Wrapper.m_InGame_PrevItem;
        public InputAction @NextItem => m_Wrapper.m_InGame_NextItem;
        public InputAction @Item1 => m_Wrapper.m_InGame_Item1;
        public InputAction @Item2 => m_Wrapper.m_InGame_Item2;
        public InputAction @Item3 => m_Wrapper.m_InGame_Item3;
        public InputAction @Item4 => m_Wrapper.m_InGame_Item4;
        public InputAction @Item5 => m_Wrapper.m_InGame_Item5;
        public InputAction @Item6 => m_Wrapper.m_InGame_Item6;
        public InputAction @Item7 => m_Wrapper.m_InGame_Item7;
        public InputAction @Item8 => m_Wrapper.m_InGame_Item8;
        public InputAction @Item9 => m_Wrapper.m_InGame_Item9;
        public InputActionMap Get() { return m_Wrapper.m_InGame; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(InGameActions set) { return set.Get(); }
        public void AddCallbacks(IInGameActions instance)
        {
            if (instance == null || m_Wrapper.m_InGameActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_InGameActionsCallbackInterfaces.Add(instance);
            @PrevItem.started += instance.OnPrevItem;
            @PrevItem.performed += instance.OnPrevItem;
            @PrevItem.canceled += instance.OnPrevItem;
            @NextItem.started += instance.OnNextItem;
            @NextItem.performed += instance.OnNextItem;
            @NextItem.canceled += instance.OnNextItem;
            @Item1.started += instance.OnItem1;
            @Item1.performed += instance.OnItem1;
            @Item1.canceled += instance.OnItem1;
            @Item2.started += instance.OnItem2;
            @Item2.performed += instance.OnItem2;
            @Item2.canceled += instance.OnItem2;
            @Item3.started += instance.OnItem3;
            @Item3.performed += instance.OnItem3;
            @Item3.canceled += instance.OnItem3;
            @Item4.started += instance.OnItem4;
            @Item4.performed += instance.OnItem4;
            @Item4.canceled += instance.OnItem4;
            @Item5.started += instance.OnItem5;
            @Item5.performed += instance.OnItem5;
            @Item5.canceled += instance.OnItem5;
            @Item6.started += instance.OnItem6;
            @Item6.performed += instance.OnItem6;
            @Item6.canceled += instance.OnItem6;
            @Item7.started += instance.OnItem7;
            @Item7.performed += instance.OnItem7;
            @Item7.canceled += instance.OnItem7;
            @Item8.started += instance.OnItem8;
            @Item8.performed += instance.OnItem8;
            @Item8.canceled += instance.OnItem8;
            @Item9.started += instance.OnItem9;
            @Item9.performed += instance.OnItem9;
            @Item9.canceled += instance.OnItem9;
        }

        private void UnregisterCallbacks(IInGameActions instance)
        {
            @PrevItem.started -= instance.OnPrevItem;
            @PrevItem.performed -= instance.OnPrevItem;
            @PrevItem.canceled -= instance.OnPrevItem;
            @NextItem.started -= instance.OnNextItem;
            @NextItem.performed -= instance.OnNextItem;
            @NextItem.canceled -= instance.OnNextItem;
            @Item1.started -= instance.OnItem1;
            @Item1.performed -= instance.OnItem1;
            @Item1.canceled -= instance.OnItem1;
            @Item2.started -= instance.OnItem2;
            @Item2.performed -= instance.OnItem2;
            @Item2.canceled -= instance.OnItem2;
            @Item3.started -= instance.OnItem3;
            @Item3.performed -= instance.OnItem3;
            @Item3.canceled -= instance.OnItem3;
            @Item4.started -= instance.OnItem4;
            @Item4.performed -= instance.OnItem4;
            @Item4.canceled -= instance.OnItem4;
            @Item5.started -= instance.OnItem5;
            @Item5.performed -= instance.OnItem5;
            @Item5.canceled -= instance.OnItem5;
            @Item6.started -= instance.OnItem6;
            @Item6.performed -= instance.OnItem6;
            @Item6.canceled -= instance.OnItem6;
            @Item7.started -= instance.OnItem7;
            @Item7.performed -= instance.OnItem7;
            @Item7.canceled -= instance.OnItem7;
            @Item8.started -= instance.OnItem8;
            @Item8.performed -= instance.OnItem8;
            @Item8.canceled -= instance.OnItem8;
            @Item9.started -= instance.OnItem9;
            @Item9.performed -= instance.OnItem9;
            @Item9.canceled -= instance.OnItem9;
        }

        public void RemoveCallbacks(IInGameActions instance)
        {
            if (m_Wrapper.m_InGameActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IInGameActions instance)
        {
            foreach (var item in m_Wrapper.m_InGameActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_InGameActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public InGameActions @InGame => new InGameActions(this);
    public interface IInGameActions
    {
        void OnPrevItem(InputAction.CallbackContext context);
        void OnNextItem(InputAction.CallbackContext context);
        void OnItem1(InputAction.CallbackContext context);
        void OnItem2(InputAction.CallbackContext context);
        void OnItem3(InputAction.CallbackContext context);
        void OnItem4(InputAction.CallbackContext context);
        void OnItem5(InputAction.CallbackContext context);
        void OnItem6(InputAction.CallbackContext context);
        void OnItem7(InputAction.CallbackContext context);
        void OnItem8(InputAction.CallbackContext context);
        void OnItem9(InputAction.CallbackContext context);
    }
}
